In [1]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split

In [2]:
%pip install mlflow dagshub

Collecting mlflow
  Downloading mlflow-3.15.1-py3-none-any.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 2.3 MB/s eta 0:00:00
Collecting dagshub
  Downloading dagshub-0.7.1-py3-none-any.whl.metadata (12 kB)
Collecting mlflow-skinny==3.15.1 (from mlflow)
  Downloading mlflow_skinny-3.15.1-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 2.9 MB/s eta 0:00:00
Collecting mlflow-tracing==3.15.1 (from mlflow)
  Downloading mlflow_tracing-3.15.1-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.14.1)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Downloading alembic-1.19.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: cryptography<50,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (49.0.0)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<27 (from mlflow)
  Downloading gunicorn-26.0.0-py3-none-any.whl.metadata (5.4 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Downloading huey-3.3.4-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<26,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.51)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (8.4.2)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.15.1->mlflow)
  Downloading databricks_sdk-0.125.0-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (0.139.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (3.1.51)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (9.0.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.42.1)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.15.1->mlflow)
  Downloading opentelemetry_proto-1.44.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.42.1)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (26.2)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (2.13.4)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (4.16.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (0.51.0)
Collecting appdirs>=1.4.4 (from dagshub)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Collecting dacite~=1.6.0 (from dagshub)
  Downloading dacite-1.6.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Collecting gql[requests] (from dagshub)
  Downloading gql-4.0.0-py3-none-any.whl.metadata (10 kB)
Collecting dataclasses-json (from dagshub)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting treelib>=1.6.4 (from dagshub)
  Downloading treelib-1.8.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pathvalidate>=3.0.0 (from dagshub)
  Downloading pathvalidate-3.3.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Collecting boto3 (from dagshub)
  Downloading boto3-1.43.67-py3-none-any.whl.metadata (6.6 kB)
Collecting semver (from dagshub)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting dagshub-annotation-converter>=0.2.0 (from dagshub)
  Downloading dagshub_annotation_converter-0.2.2-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.24.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.1.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography<50,>=43.0.0->mlflow) (2.1.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (6.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (11.3.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow) (4.0.12)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->dagshub) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.18.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.3)
Collecting botocore<1.44.0,>=1.43.67 (from boto3->dagshub)
  Downloading botocore-1.43.67-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->dagshub)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3->dagshub)
  Downloading s3transfer-0.19.2-py3-none-any.whl.metadata (1.7 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->dagshub)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json->dagshub)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting backoff<3.0,>=1.11.1 (from gql[requests]->dagshub)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography<50,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (2.49.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.15.1->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.15.1->mlflow) (0.0.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow) (5.0.3)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.15.1->mlflow) (4.1.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.15.1->mlflow) (0.63b1)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow) (2.46.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow) (3.4.9)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (0.6.4)
Downloading mlflow-3.15.1-py3-none-any.whl (11.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 85.5 MB/s eta 0:00:00
Downloading mlflow_skinny-3.15.1-py3-none-any.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 90.2 MB/s eta 0:00:00
Downloading mlflow_tracing-3.15.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 59.2 MB/s eta 0:00:00
Downloading dagshub-0.7.1-py3-none-any.whl (273 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.3/273.3 kB 21.2 MB/s eta 0:00:00
Downloading alembic-1.19.1-py3-none-any.whl (265 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 kB 22.1 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading dacite-1.6.0-py3-none-any.whl (12 kB)
Downloading dagshub_annotation_converter-0.2.2-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 6.0 MB/s eta 0:00:00
Downloading docker-7.2.0-py3-none-any.whl (148 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 14.0 MB/s eta 0:00:00
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 10.7 MB/s eta 0:00:00
Downloading gunicorn-26.0.0-py3-none-any.whl (212 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 16.7 MB/s eta 0:00:00
Downloading huey-3.3.4-py3-none-any.whl (123 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.9/123.9 kB 9.6 MB/s eta 0:00:00
Downloading pathvalidate-3.3.1-py3-none-any.whl (24 kB)
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 10.9 MB/s eta 0:00:00
Downloading treelib-1.8.0-py3-none-any.whl (30 kB)
Downloading boto3-1.43.67-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 9.4 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading botocore-1.43.67-py3-none-any.whl (15.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 89.3 MB/s eta 0:00:00
Downloading databricks_sdk-0.125.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 55.2 MB/s eta 0:00:00
Downloading graphql_core-3.2.11-py3-none-any.whl (214 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.9/214.9 kB 17.0 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 3.9 MB/s eta 0:00:00
Downloading opentelemetry_proto-1.44.0-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 6.2 MB/s eta 0:00:00
Downloading s3transfer-0.19.2-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 7.7 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading gql-4.0.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 6.9 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: huey, appdirs, treelib, semver, pathvalidate, opentelemetry-proto, mypy-extensions, marshmallow, jmespath, gunicorn, graphql-core, dacite, backoff, typing-inspect, graphql-relay, gql, docker, botocore, alembic, skops, s3transfer, graphene, Flask-CORS, dataclasses-json, dagshub-annotation-converter, databricks-sdk, boto3, mlflow-tracing, mlflow-skinny, dagshub, mlflow
Successfully installed Flask-CORS-6.0.5 alembic-1.19.1 appdirs-1.4.4 backoff-2.2.1 boto3-1.43.67 botocore-1.43.67 dacite-1.6.0 dagshub-0.7.1 dagshub-annotation-converter-0.2.2 databricks-sdk-0.125.0 dataclasses-json-0.6.7 docker-7.2.0 gql-4.0.0 graphene-3.4.3 graphql-core-3.2.11 graphql-relay-3.2.0 gunicorn-26.0.0 huey-3.3.4 jmespath-1.1.0 marshmallow-3.26.2 mlflow-3.15.1 mlflow-skinny-3.15.1 mlflow-tracing-3.15.1 mypy-extensions-1.1.0 opentelemetry-proto-1.44.0 pathvalidate-3.3.1 s3transfer-0.19.2 semver-3.0.4 skops-0.14.0 treelib-1.8.0 typing-inspect-0.9.0

In [3]:
import sys
!{sys.executable} -m pip install mlflow dagshub
import mlflow

mlflow.set_tracking_uri("https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow")

Requirement already satisfied: mlflow in /usr/local/lib/python3.12/dist-packages (3.15.1)
Requirement already satisfied: dagshub in /usr/local/lib/python3.12/dist-packages (0.7.1)
Requirement already satisfied: mlflow-skinny==3.15.1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.15.1)
Requirement already satisfied: mlflow-tracing==3.15.1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.15.1)
Requirement already satisfied: Flask-CORS<7 in /usr/local/lib/python3.12/dist-packages (from mlflow) (6.0.5)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.14.1)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.19.1)
Requirement already satisfied: cryptography<50,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (49.0.0)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (7.2.0)
Requirement already satisfied: graphene<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.4.3)
Requirement already satisfied: gunicorn<27 in /usr/local/lib/python3.12/dist-packages (from mlflow) (26.0.0)
Requirement already satisfied: huey<4,>=2.5.4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.3.4)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<26,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Requirement already satisfied: skops<1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.51)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (8.4.2)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (0.125.0)
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (0.139.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (3.1.51)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (9.0.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.42.1)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.44.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.42.1)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (26.2)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (2.13.4)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (4.16.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (0.51.0)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.4.4)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Requirement already satisfied: dacite~=1.6.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.6.0)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Requirement already satisfied: gql[requests] in /usr/local/lib/python3.12/dist-packages (from dagshub) (4.0.0)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.6.7)
Requirement already satisfied: treelib>=1.6.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.8.0)
Requirement already satisfied: pathvalidate>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.3.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.43.67)
Requirement already satisfied: semver in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.0.4)
Requirement already satisfied: dagshub-annotation-converter>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.2.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.24.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.1.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography<50,>=43.0.0->mlflow) (2.1.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (6.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (11.3.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow) (4.0.12)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.11)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->dagshub) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.18.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.3)
Requirement already satisfied: botocore<1.44.0,>=1.43.67 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.43.67)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (0.19.2)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (0.9.0)
Requirement already satisfied: backoff<3.0,>=1.11.1 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (2.2.1)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography<50,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (2.49.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.15.1->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.15.1->mlflow) (0.0.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow) (5.0.3)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.15.1->mlflow) (4.1.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.15.1->mlflow) (0.63b1)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow) (2.46.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow) (3.4.9)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.1.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (0.6.4)

In [4]:
import dagshub
dagshub.init(repo_owner='bhargavivyshnavi04', repo_name='Swiggy-Delivery-Time-Prediction', mlflow=True)

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=d8f4776b-68af-47f9-8026-537c8c984c3f&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=e013053eb3995e7d120f7bae1c05ab61b8eb6fcb85762d298ade5d98b3af1702

Accessing as bhargavivyshnavi04

Initialized MLflow to track repo "bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction"

Repository bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction initialized!

In [5]:
import mlflow

In [6]:
import dagshub
dagshub.init(repo_owner='bhargavivyshnavi04', repo_name='Swiggy-Delivery-Time-Prediction', mlflow=True)

Initialized MLflow to track repo "bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction"

Repository bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction initialized!

In [9]:
# mlflow experiment

mlflow.set_experiment("Exp 4 - LGBM HyperParameter Tuning")

<Experiment: artifact_location='mlflow-artifacts:/16d360b29dd142098a5eefe17965cb2e', creation_time=1786212002162, effective_trace_archival_retention=None, experiment_id='6', last_update_time=1786212002162, lifecycle_stage='active', name='Exp 4 - LGBM HyperParameter Tuning', tags={}, trace_location=None, workspace='default'>

In [10]:
from sklearn import set_config

set_config(transform_output="pandas")

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [12]:
path = "/content/drive/MyDrive/datasets/swiggy_cleaned.csv"

df = pd.read_csv(path)
df.head()

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance,distance_type
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,sunny,high,...,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149,short
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,stormy,jam,...,BANG,25,3,friday,0,5.0,19.0,evening,20.183530,very_long
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,sandstorms,low,...,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758,short
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,sunny,medium,...,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401,medium
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,cloudy,high,...,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138,medium

In [13]:
# drop columns not required for model input

columns_to_drop =  ['rider_id',
                    'restaurant_latitude',
                    'restaurant_longitude',
                    'delivery_latitude',
                    'delivery_longitude',
                    'order_date',
                    "order_time_hour",
                    "order_day",
                    "city_name",
                    "order_day_of_week",
                    "order_month"]

df.drop(columns=columns_to_drop, inplace=True)

df

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,1,15.0,morning,3.025149,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,0,5.0,evening,20.183530,very_long
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,1,15.0,morning,1.552758,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,0,10.0,evening,7.790401,medium
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,1,15.0,afternoon,6.210138,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45497,30.0,4.8,windy,high,1,meal,motorcycle,0.0,no,metropolitian,32,0,10.0,morning,1.489846,short
45498,21.0,4.6,windy,jam,0,buffet,motorcycle,1.0,no,metropolitian,36,0,15.0,evening,NaN,NaN
45499,30.0,4.9,cloudy,low,1,drinks,scooter,0.0,no,metropolitian,16,0,15.0,night,4.657195,short
45500,20.0,4.7,cloudy,high,0,snack,motorcycle,1.0,no,metropolitian,26,0,5.0,afternoon,6.232393,medium
45501,23.0,4.9,fog,medium,2,snack,scooter,1.0,no,metropolitian,36,0,5.0,afternoon,12.074396,long

In [14]:
# check for missing values

df.isna().sum()

age                    1854
ratings                1908
weather                 525
traffic                 510
vehicle_condition         0
type_of_order             0
type_of_vehicle           0
multiple_deliveries     993
festival                228
city_type              1198
time_taken                0
is_weekend                0
pickup_time_minutes    1640
order_time_of_day      2070
distance               3630
distance_type          3630
dtype: int64

In [15]:
temp_df = df.copy().dropna()

In [16]:
# split into X and y

X = temp_df.drop(columns='time_taken')
y = temp_df['time_taken']

X

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,1,15.0,morning,3.025149,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,0,5.0,evening,20.183530,very_long
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,1,15.0,morning,1.552758,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,0,10.0,evening,7.790401,medium
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,1,15.0,afternoon,6.210138,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45496,35.0,4.2,windy,jam,2,drinks,motorcycle,1.0,no,metropolitian,0,10.0,night,16.600272,very_long
45497,30.0,4.8,windy,high,1,meal,motorcycle,0.0,no,metropolitian,0,10.0,morning,1.489846,short
45499,30.0,4.9,cloudy,low,1,drinks,scooter,0.0,no,metropolitian,0,15.0,night,4.657195,short
45500,20.0,4.7,cloudy,high,0,snack,motorcycle,1.0,no,metropolitian,0,5.0,afternoon,6.232393,medium
45501,23.0,4.9,fog,medium,2,snack,scooter,1.0,no,metropolitian,0,5.0,afternoon,12.074396,long

In [17]:
# train test split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
print("The size of train data is",X_train.shape)
print("The shape of test data is",X_test.shape)

The size of train data is (30156, 15)
The shape of test data is (7539, 15)

In [19]:
# missing values in train data

X_train.isna().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
is_weekend             0
pickup_time_minutes    0
order_time_of_day      0
distance               0
distance_type          0
dtype: int64

In [20]:
# transform target column

pt = PowerTransformer()

y_train_pt = pt.fit_transform(y_train.values.reshape(-1,1))
y_test_pt = pt.transform(y_test.values.reshape(-1,1))

In [21]:
num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather',
                    'type_of_order',
                    'type_of_vehicle',
                    "festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [22]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

In [23]:
# build a preprocessor

preprocessor = ColumnTransformer(transformers=[
    ("scale", MinMaxScaler(), num_cols),
    ("nominal_encode", OneHotEncoder(drop="first",handle_unknown="ignore",
                                     sparse_output=False), nominal_cat_cols),
    ("ordinal_encode", OrdinalEncoder(categories=[traffic_order,distance_type_order],
                                      encoded_missing_value=-999,
                                      handle_unknown="use_encoded_value",
                                      unknown_value=-1), ordinal_cat_cols)
],remainder="passthrough",n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)


preprocessor

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(),
                                 ['age', 'ratings', 'pickup_time_minutes',
                                  'distance']),
                                ('nominal_encode',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_type', 'is_weekend',
                                  'order_time_of_day']),
                                ('ordinal_encode',
                                 OrdinalEncoder(categories=[['low', 'medium',
                                                             'high', 'jam'],
                                                            ['short', 'medium',
                                                             'long',
                                                             'very_long']],
                                                encoded_missing_value=-999,
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['traffic', 'distance_type'])],
                  verbose_feature_names_out=False)

In [24]:
# build the pipeline

processing_pipeline = Pipeline(steps=[
                                # ("simple_imputer",simple_imputer),
                                ("preprocess",preprocessor)
                                # ("knn_imputer",knn_imputer)
                            ])

processing_pipeline

Pipeline(steps=[('preprocess',
                 ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                                   remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  ['age', 'ratings',
                                                   'pickup_time_minutes',
                                                   'distance']),
                                                 ('nominal_encode',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['weather', 'type_of_order',
                                                   'type_of_vehicle',
                                                   'festival', 'city_type',
                                                   'is_weekend',
                                                   'order_time_of_day']),
                                                 ('ordinal_encode',
                                                  OrdinalEncoder(categories=[['low',
                                                                              'medium',
                                                                              'high',
                                                                              'jam'],
                                                                             ['short',
                                                                              'medium',
                                                                              'long',
                                                                              'very_long']],
                                                                 encoded_missing_value=-999,
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['traffic',
                                                   'distance_type'])],
                                   verbose_feature_names_out=False))])

In [25]:
# do data preprocessing

X_train_trans = processing_pipeline.fit_transform(X_train)

X_test_trans = processing_pipeline.transform(X_test)

In [26]:
%pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.19.1)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 20.0 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.12.0 optuna-4.9.0

In [27]:
from lightgbm import LGBMRegressor
import optuna

In [30]:
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.compose import TransformedTargetRegressor
from sklearn.model_selection import cross_val_score

In [28]:
def objective(trial):
    with mlflow.start_run(nested=True):
        params = {
            "n_estimators": trial.suggest_int("n_estimators",10,200),
            "max_depth": trial.suggest_int("max_depth",1,40),
            "learning_rate": trial.suggest_float("learning_rate",0.1,0.8),
            "subsample": trial.suggest_float("subsample",0.5,1),
            "min_child_weight": trial.suggest_int("min_child_weight",5,20),
            "min_split_gain": trial.suggest_float("min_split_gain",0,10),
            "reg_lambda": trial.suggest_float("reg_lambda",0,100),
            "random_state": 42,
            "n_jobs": -1,
        }

        # log model parameters
        mlflow.log_params(params)

        xgb_reg = LGBMRegressor(**params)
        model = TransformedTargetRegressor(regressor=xgb_reg,transformer=pt)

        # train the model
        model.fit(X_train_trans,y_train)

        # get the predictions
        y_pred_train = model.predict(X_train_trans)
        y_pred_test = model.predict(X_test_trans)


        # perform cross validation
        cv_score = cross_val_score(model,
                                X_train_trans,
                                y_train,
                                cv=5,
                                scoring="neg_mean_absolute_error",
                                n_jobs=-1)

        # mean score
        mean_score = -(cv_score.mean())
        # log avg cross val error
        mlflow.log_metric("cross_val_error",mean_score)

        return mean_score

In [33]:
# create optuna study
study = optuna.create_study(direction="minimize")

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study.optimize(objective,n_trials=50,n_jobs=-1,show_progress_bar=True)

    # log the best parameters
    mlflow.log_params(study.best_params)

    # log the best score
    mlflow.log_metric("best_score",study.best_value)

    # train the model on best parameters
    best_lgbm = LGBMRegressor(**study.best_params)

    best_lgbm.fit(X_train_trans,y_train_pt.values.ravel())

    # get the predictions
    y_pred_train = best_lgbm.predict(X_train_trans)
    y_pred_test = best_lgbm.predict(X_test_trans)

    # get the actual predictions values
    y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
    y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))


    # perform cross validation
    model = TransformedTargetRegressor(regressor=best_lgbm,
                                        transformer=pt)


    scores = cross_val_score(model,
                         X_train_trans,
                         y_train,
                         scoring="neg_mean_absolute_error",
                         cv=5,n_jobs=-1)

    # log metrics
    mlflow.log_metric("training_error",mean_absolute_error(y_train,y_pred_train_org))
    mlflow.log_metric("test_error",mean_absolute_error(y_test,y_pred_test_org))
    mlflow.log_metric("training_r2",r2_score(y_train,y_pred_train_org))
    mlflow.log_metric("test_r2",r2_score(y_test,y_pred_test_org))
    mlflow.log_metric("cross_val",- scores.mean())

    # log the best model
    # mlflow.sklearn.log_model(best_lgbm,artifact_path="model")
    # model_info = mlflow.sklearn.log_model(
    # best_rf,
    # name="model"
# )/

import mlflow.lightgbm

model_info = mlflow.lightgbm.log_model(
    best_lgbm,
    name="model"
)

[I 2026-08-08 18:27:10,303] A new study created in memory with name: no-name-9cd54d79-77ec-466d-b930-8703ad7ff764

  0%|          | 0/50 [00:00<?, ?it/s]

🏃 View run salty-cat-419 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/31e5dc2e55b8407caec5fc1a45848c57
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:27:15,192] Trial 1 finished with value: 3.743219392184879 and parameters: {'n_estimators': 43, 'max_depth': 40, 'learning_rate': 0.6431838530971737, 'subsample': 0.7158761966176898, 'min_child_weight': 13, 'min_split_gain': 8.717481232656425, 'reg_lambda': 60.32969941969867}. Best is trial 1 with value: 3.743219392184879.
🏃 View run angry-mule-163 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/81ff7102861146ff89804d7f8883a4b9
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:27:18,433] Trial 0 finished with value: 3.3424179164456476 and parameters: {'n_estimators': 132, 'max_depth': 24, 'learning_rate': 0.10421369756258408, 'subsample': 0.6192275077993848, 'min_child_weight': 13, 'min_split_gain': 0.6379975756278788, 'reg_lambda': 47.63021822482748}. Best is trial 0 with value: 3.3424179164456476.
🏃 View run zealous-flea-454 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/76dd196d1b2647edb92582e174a05224
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:27:19,765] Trial 2 finished with value: 4.032058781480574 and parameters: {'n_estimators': 12, 'max_depth': 19, 'learning_rate': 0.14391129276858275, 'subsample': 0.8962695174346536, 'min_child_weight': 14, 'min_split_gain': 9.923538232058553, 'reg_lambda': 20.66451665694695}. Best is trial 0 with value: 3.3424179164456476.
🏃 View run defiant-turtle-254 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/0fee63fe38554a638c10ab91e8cbeaf5
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
🏃 View run traveling-goat-68 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/86760aa7f74741cf886035f9b29ccc81
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:27:29,768] Trial 4 finished with value: 3.595224772624907 and parameters: {'n_estimators': 93, 'max_depth': 32, 'learning_rate': 0.21751063165343942, 'subsample': 0.5366224012473251, 'min_child_weight': 7, 'min_split_gain': 3.610995473547285, 'reg_lambda': 45.89499075760658}. Best is trial 0 with value: 3.3424179164456476.
[I 2026-08-08 18:27:29,771] Trial 3 finished with value: 3.5187022816925846 and parameters: {'n_estimators': 193, 'max_depth': 37, 'learning_rate': 0.3509028292528188, 'subsample': 0.8999901798831059, 'min_child_weight': 10, 'min_split_gain': 2.945811167100473, 'reg_lambda': 64.04549774600811}. Best is trial 0 with value: 3.3424179164456476.
🏃 View run sneaky-bee-557 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/1b73879682d74a0fa2086c3a959db0e2
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
🏃 View run gaudy-ray-130 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/f0164ff92d694d9bb9b2321633646fc5
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:27:35,935] Trial 6 finished with value: 3.7584563347231823 and parameters: {'n_estimators': 153, 'max_depth': 16, 'learning_rate': 0.7643056736596562, 'subsample': 0.8134262512971178, 'min_child_weight': 7, 'min_split_gain': 7.3472744406305734, 'reg_lambda': 38.79855023923192}. Best is trial 0 with value: 3.3424179164456476.
[I 2026-08-08 18:27:35,988] Trial 5 finished with value: 3.2785854845490237 and parameters: {'n_estimators': 57, 'max_depth': 11, 'learning_rate': 0.25390518838764264, 'subsample': 0.9546773841888612, 'min_child_weight': 14, 'min_split_gain': 0.3423973693145177, 'reg_lambda': 60.20213237352207}. Best is trial 5 with value: 3.2785854845490237.
🏃 View run languid-smelt-439 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/25875deddb7b424a9d21344988c1f6bd
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:27:50,529] Trial 8 finished with value: 3.7576783031951324 and parameters: {'n_estimators': 16, 'max_depth': 10, 'learning_rate': 0.4120460378064673, 'subsample': 0.7110433459975216, 'min_child_weight': 19, 'min_split_gain': 8.814291909186615, 'reg_lambda': 6.757571763541459}. Best is trial 5 with value: 3.2785854845490237.
🏃 View run wise-cub-63 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/0b3a7fda52e748dba81dc15196f241ea
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:27:54,715] Trial 7 finished with value: 3.745881667677517 and parameters: {'n_estimators': 95, 'max_depth': 15, 'learning_rate': 0.10662400145613657, 'subsample': 0.6677444867764177, 'min_child_weight': 14, 'min_split_gain': 7.08324455382588, 'reg_lambda': 99.35897738324157}. Best is trial 5 with value: 3.2785854845490237.
🏃 View run sassy-fawn-291 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/1018e539b2f24999a1a9fa2c78ec73e6
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
🏃 View run spiffy-skink-563 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/8e322d2d53d14e82afca315edc4cb699
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:28:14,510] Trial 9 finished with value: 3.5287133597819236 and parameters: {'n_estimators': 196, 'max_depth': 16, 'learning_rate': 0.5411789795137574, 'subsample': 0.949184832335907, 'min_child_weight': 10, 'min_split_gain': 1.8573511470797988, 'reg_lambda': 10.03789093227182}. Best is trial 5 with value: 3.2785854845490237.
[I 2026-08-08 18:28:18,529] Trial 10 finished with value: 3.5798221537471306 and parameters: {'n_estimators': 26, 'max_depth': 19, 'learning_rate': 0.6736774627906014, 'subsample': 0.5897268098005468, 'min_child_weight': 14, 'min_split_gain': 2.5217509315481768, 'reg_lambda': 87.58706561732379}. Best is trial 5 with value: 3.2785854845490237.
🏃 View run agreeable-pug-399 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/9f617bb053e34d96b504d89d908a0b8d
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
🏃 View run amusing-zebra-114 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/dd26bc59558a4411a7e92f410e3a75d2
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:28:42,558] Trial 12 finished with value: 4.301861087034866 and parameters: {'n_estimators': 94, 'max_depth': 1, 'learning_rate': 0.2970472535652783, 'subsample': 0.9916683783042627, 'min_child_weight': 18, 'min_split_gain': 0.2127620388787439, 'reg_lambda': 68.8542819645159}. Best is trial 5 with value: 3.2785854845490237.
[I 2026-08-08 18:28:46,522] Trial 11 finished with value: 4.315198375269634 and parameters: {'n_estimators': 89, 'max_depth': 1, 'learning_rate': 0.2719936333899523, 'subsample': 0.9923295937258703, 'min_child_weight': 19, 'min_split_gain': 0.4153955972142329, 'reg_lambda': 69.34166513120121}. Best is trial 5 with value: 3.2785854845490237.
🏃 View run languid-quail-93 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/0d868ddcf20d41e88a9ac6365d158121
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:28:50,724] Trial 13 finished with value: 3.1765584156174747 and parameters: {'n_estimators': 136, 'max_depth': 29, 'learning_rate': 0.24984659213378066, 'subsample': 0.7894567173855567, 'min_child_weight': 17, 'min_split_gain': 0.10917347400124217, 'reg_lambda': 38.304319083172786}. Best is trial 13 with value: 3.1765584156174747.
🏃 View run abundant-skink-135 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/ed8fabc9473d4374b719a04b2689d0ad
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:28:53,096] Trial 14 finished with value: 3.636626470042799 and parameters: {'n_estimators': 147, 'max_depth': 29, 'learning_rate': 0.4301283283158315, 'subsample': 0.8039044844281015, 'min_child_weight': 16, 'min_split_gain': 4.857174384450169, 'reg_lambda': 36.90112712302952}. Best is trial 13 with value: 3.1765584156174747.
🏃 View run bald-bat-229 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/7292ac2003954f4c9fc408f6beed3a14
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
🏃 View run glamorous-vole-823 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/216ea3badd4042fc914464edd8a5c62e
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:29:10,542] Trial 16 finished with value: 3.4606761631166307 and parameters: {'n_estimators': 58, 'max_depth': 10, 'learning_rate': 0.21367311785036489, 'subsample': 0.8120690858392932, 'min_child_weight': 16, 'min_split_gain': 1.4102847131889353, 'reg_lambda': 27.815842456512268}. Best is trial 13 with value: 3.1765584156174747.
[I 2026-08-08 18:29:14,542] Trial 15 finished with value: 3.471296013533511 and parameters: {'n_estimators': 62, 'max_depth': 8, 'learning_rate': 0.21512250612677267, 'subsample': 0.807431303026139, 'min_child_weight': 17, 'min_split_gain': 1.440988204260297, 'reg_lambda': 26.227361885256762}. Best is trial 13 with value: 3.1765584156174747.
🏃 View run delicate-rat-154 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/8d4f7118e0fb4eab9696877824bedf5c
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:29:21,284] Trial 17 finished with value: 3.631775713954358 and parameters: {'n_estimators': 123, 'max_depth': 27, 'learning_rate': 0.45997807229109483, 'subsample': 0.873504075206477, 'min_child_weight': 17, 'min_split_gain': 3.8498219186089893, 'reg_lambda': 81.73902638641263}. Best is trial 13 with value: 3.1765584156174747.
🏃 View run puzzled-crow-783 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/38397e14f0ff44ea8995e7f444a28051
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:29:25,861] Trial 18 finished with value: 3.653007966046341 and parameters: {'n_estimators': 123, 'max_depth': 24, 'learning_rate': 0.46170869019900307, 'subsample': 0.8810929778116603, 'min_child_weight': 11, 'min_split_gain': 4.250444151686155, 'reg_lambda': 54.859742842823195}. Best is trial 13 with value: 3.1765584156174747.
🏃 View run kindly-moth-512 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/3ca2a02f169440a6966331492dbe8c30
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
🏃 View run puzzled-ox-324 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/0168c1ea0c094da4a76d4cdc73816b5d
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:29:46,301] Trial 20 finished with value: 3.2208828321320673 and parameters: {'n_estimators': 172, 'max_depth': 35, 'learning_rate': 0.3261179390554625, 'subsample': 0.7433821201120737, 'min_child_weight': 20, 'min_split_gain': 0.11818815336536073, 'reg_lambda': 76.19075011947737}. Best is trial 13 with value: 3.1765584156174747.
[I 2026-08-08 18:29:46,590] Trial 19 finished with value: 3.2495700793198097 and parameters: {'n_estimators': 173, 'max_depth': 34, 'learning_rate': 0.33304254045500986, 'subsample': 0.7466572912773193, 'min_child_weight': 12, 'min_split_gain': 0.16366299519555508, 'reg_lambda': 77.1303341097839}. Best is trial 13 with value: 3.1765584156174747.
🏃 View run wistful-loon-374 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/9b1c400948084f54ad30675b0b84abee
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:29:54,743] Trial 21 finished with value: 3.4714684582485704 and parameters: {'n_estimators': 172, 'max_depth': 35, 'learning_rate': 0.34380520366118417, 'subsample': 0.7486650397553585, 'min_child_weight': 20, 'min_split_gain': 1.358574339471735, 'reg_lambda': 79.32079705715682}. Best is trial 13 with value: 3.1765584156174747.
🏃 View run skillful-fish-892 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/a163b06ecb284fe886b714515d99bd6f
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
🏃 View run crawling-stag-373 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/72ad29adebf84a7f84d20caa1a480e88
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:30:05,321] Trial 22 finished with value: 3.479336131595294 and parameters: {'n_estimators': 172, 'max_depth': 36, 'learning_rate': 0.34201344808670303, 'subsample': 0.7409743709587601, 'min_child_weight': 20, 'min_split_gain': 1.3952238161114103, 'reg_lambda': 85.87438579431456}. Best is trial 13 with value: 3.1765584156174747.
[I 2026-08-08 18:30:05,393] Trial 23 finished with value: 3.160201027678494 and parameters: {'n_estimators': 170, 'max_depth': 32, 'learning_rate': 0.33781681851244505, 'subsample': 0.7552389920520288, 'min_child_weight': 20, 'min_split_gain': 0.021029939865750746, 'reg_lambda': 96.33718451413448}. Best is trial 23 with value: 3.160201027678494.
🏃 View run caring-bat-585 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/ceb7245bc67743cab59a214ffeb42d70
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:30:11,502] Trial 24 finished with value: 3.496274903010037 and parameters: {'n_estimators': 151, 'max_depth': 30, 'learning_rate': 0.3888356686827706, 'subsample': 0.6606211202932146, 'min_child_weight': 18, 'min_split_gain': 2.1959002218323733, 'reg_lambda': 99.53558308845153}. Best is trial 23 with value: 3.160201027678494.
🏃 View run whimsical-snail-204 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/e49c83b15c22414d8e7520899ca31936
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:30:18,562] Trial 25 finished with value: 3.552125814675965 and parameters: {'n_estimators': 156, 'max_depth': 30, 'learning_rate': 0.5363920246508764, 'subsample': 0.6627612844929375, 'min_child_weight': 18, 'min_split_gain': 2.503642508470274, 'reg_lambda': 95.77733157316793}. Best is trial 23 with value: 3.160201027678494.
🏃 View run smiling-stag-946 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/c2955033bfd74e80895af44f836eb3b3
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:30:22,788] Trial 26 finished with value: 3.4363168309097984 and parameters: {'n_estimators': 181, 'max_depth': 40, 'learning_rate': 0.5181418502636492, 'subsample': 0.7777436101401733, 'min_child_weight': 20, 'min_split_gain': 1.0554713190576044, 'reg_lambda': 88.93100380635329}. Best is trial 23 with value: 3.160201027678494.
🏃 View run orderly-shad-158 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/d050bed0601945f7924d966aa2c13a04
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:30:30,797] Trial 27 finished with value: 3.4382005891010627 and parameters: {'n_estimators': 185, 'max_depth': 40, 'learning_rate': 0.1619337328637797, 'subsample': 0.769009266343568, 'min_child_weight': 20, 'min_split_gain': 0.9857208697293076, 'reg_lambda': 89.62971861524142}. Best is trial 23 with value: 3.160201027678494.
🏃 View run worried-ox-395 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/99eda75979b24cfaaaaaed070c687ead
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:30:46,196] Trial 29 finished with value: 3.1633207841590347 and parameters: {'n_estimators': 134, 'max_depth': 24, 'learning_rate': 0.28384526631566737, 'subsample': 0.8481201234158314, 'min_child_weight': 16, 'min_split_gain': 0.12631131997522566, 'reg_lambda': 0.31798029423464413}. Best is trial 23 with value: 3.160201027678494.
🏃 View run polite-sloth-624 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/b41dfc220f0a41b3883e27345bb36623
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:30:46,833] Trial 28 finished with value: 3.4199764281323546 and parameters: {'n_estimators': 135, 'max_depth': 25, 'learning_rate': 0.1727509728032602, 'subsample': 0.8551740821135542, 'min_child_weight': 16, 'min_split_gain': 0.9305782283813688, 'reg_lambda': 73.23775589491589}. Best is trial 23 with value: 3.160201027678494.
🏃 View run rambunctious-eel-97 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/000619ebad224e63ba126fa702b4278f
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:31:02,811] Trial 31 finished with value: 3.507258023898669 and parameters: {'n_estimators': 113, 'max_depth': 27, 'learning_rate': 0.27988085063317136, 'subsample': 0.8431858844973273, 'min_child_weight': 15, 'min_split_gain': 3.1203231548995225, 'reg_lambda': 0.4042797557741458}. Best is trial 23 with value: 3.160201027678494.
🏃 View run big-skunk-884 at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6/runs/9988892d042b4706996566f7a16529da
🧪 View experiment at: https://dagshub.com/bhargavivyshnavi04/Swiggy-Delivery-Time-Prediction.mlflow/#/experiments/6
[I 2026-08-08 18:31:14,588] Trial 30 finished with value: 3.533907261969665 and parameters: {'n_estimators': 114, 'max_depth': 21, 'learning_rate': 0.2620513200592256, 'subsample': 0.8454824773589477, 'min_child_weight': 5, 'min_split_gain': 3.2087941105793623, 'reg_lambda': 18.222314017272257}. Best is trial 23 with value: 3.160201027678494.